collections:
  projects:
    output: true

permalink: /blog/:categories/:title.html

plugins:
  - jekyll-feed

sass:
  sass_dir: /assets/stylesheets/

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge